### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tommoor** [smakinson/Pusher-ActionScript-Library#5]
Is there some documentation on how to use this library anywhere?

**Comment by smakinson** [comment]
I just added some demo files that never made it up. Its not much as far as docs go, but it should help some. You need to put the auth.php page on your server.

**Comment by tommoor** [comment]
Great! 

I actually figured it out but didn't use this lib originally because of a lack of documentation. The other lib linked from the pusher docs I couldn't get to work at all after hours of debugging.

Hopefully this will help others that end up here :-)
