### ISSUE TITLE
Pusher dispatchPusherEvent

### ISSUE THREAD

**Issue by Seke1412** [smakinson/Pusher-ActionScript-Library#6]
Hey guys,

I'm a flash developer. I've just discovered Pusher recently and read through the code and example and write a "hello world" integrate with Pusher. Here is the code

<code>
import com.dozeo.pusheras.events._;
import com.dozeo.pusheras.utils._;
import com.adobe.serialization.json._;
import com.dozeo.pusheras.channel._;
import com.dozeo.pusheras._;
import com.dozeo.pusheras.vo._;
<code>
var testChannel:PusherChannel;
var pusherOptions:PusherOptions = new PusherOptions();
pusherOptions.applicationKey = '868310468f8192695xxx;
pusherOptions.origin = 'http://my_domain/testchat/';
pusherOptions.auth_endpoint = "http://my_domain/testchat/check.php"
var pusher:Pusher = new Pusher(pusherOptions);
pusher.addEventListener(PusherEvent.CONNECTION_ESTABLISHED, onPusherConnect);
pusher.connect();
function onPusherConnect(e:PusherEvent):void{
    testChannel = pusher.subscribe('CHATROOM-0');
    testChannel.addEventListener('test-mess', testChannel_MY_EVENT);
stage.addEventListener(MouseEvent.CLICK, stageClick)
}
function testChannel_MY_EVENT(e:PusherEvent):void{
    trace(e.toJSON())
}
function stageClick(e:MouseEvent){
    var pusherEvent:PusherEvent = new PusherEvent('message-created');
    pusherEvent.data = {"user":"Seke","content":"hello"};
    pusherEvent.channel = "CHATROOM-0";
    testChannel.dispatchPusherEvent(pusherEvent)
}

with this code i can receive data through testChannel_MY_EVENT, but i cannot post anything, it alert something like this:

<code>
cannot parse data part! Message: Unexpected o encountered <  [object Object]

It sounds like something wrong with the dispatchPusherEvent, but i can't figure it out for days :(. Does anyone know how to post a message through Pusher using AS3. Please help :(.

**Comment by smakinson** [comment]
In your function testChannel_MY_EVENT you are tracing the event to json when I believe you are trying to get the json that would be in the e.data property.

**Comment by Seke1412** [comment]
Thank smakinson, i've just check it again. The testChannel_MY_EVENT function work properply and i can read data from Pusher. 
The problem is that i cannot push data to Pusher through testChannel.dispatchPusherEvent in the stageClick function, it just keeps throwing that crazy error :(.

**Comment by smakinson** [comment]
Looking again, I believe you are on the wrong github repo with your question. There are 2 libraries and it appears you are using the other one by dozeo.

**Comment by Seke1412** [comment]
Oh, sorry. Can you show me how flash as3 work with Pusher using github libs? Thx you so much.

**Comment by smakinson** [comment]
I am not familiar with the other library, but from the error you are seeing my first guess would be that the data being sent might be invalid json.

**Comment by Seke1412** [comment]
I think so, too. But i've just failed to figure it out for 2 days. What a pity your libs is coding for flex, but i'm working with Flash :((. Thanks so much smakinson, i appreciate it.

**Comment by smakinson** [comment]
Its not specific for flex, the demo just happens to use it as a quick layout. I had someone else recently switch over because of some troubles he could not figure out. To be honest I have not kept up with pusher for a while, but as far as I know this library still works fine. I based it on the javascript library at the time.

**Comment by Seke1412** [comment]
Let me try it. Thank smakinson
