### ISSUE TITLE
Problem with JSON

### ISSUE THREAD

**Issue by Seke1412** [smakinson/Pusher-ActionScript-Library#7]
Hi smakinson;

i've read your Lib and do a small test

import com.pusher._;
import com.pusher.events._;
import com.pusher.channel._;
import com.pusher.auth._;
import com.pusher.data.*;

var pusher:Pusher = new Pusher("868310468f8192695852","http://dev3.sofresh.vn/testchat/");
pusher.connect();
var channel:Channel = 
pusher.subscribe('CHATROOM-0')
pusher.bind("test-mess",testChannel);
function testChannel(e:PusherEvent){
    trace(e.data)
}

but i get stuck with the JSON
..\com\pusher\Pusher.as, Line 370   1120: Access of undefined property JSON.

i also try the asCoreLibs but it still doesn't work. Please help me :(

**Comment by Seke1412** [comment]
The JSON problem seem to fine with flash player 11.+;
but i cannot broadcast my event :(. Any ideas guys :(((((. Save me.....

import com.pusher._;
import com.pusher.events._;
import com.pusher.channel._;
import com.pusher.auth._;
import com.pusher.data.*;

var pusher:Pusher = new Pusher("868310468f8192695xxx","http://mydomain/testchat/");
pusher.connect();
var channel:Channel
channel = pusher.subscribe('CHATROOM-0')

channel.bind("test-mess", testChannel)
function testChannel(data){
    trace(data.user, data.content)
    stage.addEventListener(MouseEvent.CLICK, mouseClick)
}

function mouseClick(e:MouseEvent){
    var d = {user:"SEKE", content:"HELLO THE F"}
    channel.dispatch("test-mess",d);
    //pusher.sendEvent("test-mess",d,channel.name)
}

**Comment by smakinson** [comment]
Take a look in the demo folder. You may just need to set up the serverside authorizer. The demo uses a php version.

**Comment by Seke1412** [comment]
i just take a look at your demo. I found that you write your demo with presence channel. But i need to use Pusher as a public channel. But it throw an error "Currently the basic Channel does not support trigger calls." as follow

var channel:Channel;
pusher.connect();
channel = pusher.subscribe("CHATROOM-0")
channel.bind("test-mess", testChannel)

stage.addEventListener(MouseEvent.CLICK, mouseClick)

function testChannel(data){
    trace(data.user, data.content)
}

function mouseClick(e:MouseEvent){
    var d = {user:"SEKE", content:"HELLO"}
    channel.trigger("test-mess", d)
}

what should i do next :(

**Comment by smakinson** [comment]
Pusher relies on some prefixes when naming things. channel.bindToClient() will auto add the client event prefix. Try using that instead of bind().

Also trigger can not be called on Channel, that method simply throws the error you are seeing. I believe its that way because the javascript version at the time I ported it also had that limitation.

**Comment by Seke1412** [comment]
Thank so much smakinson. I got your idea, but instead of using trigger method, what method/event should i use to broadcast my data? pusher.sendToLocal/ channel.dispatchPusherEvent/ or something else?

**Comment by smakinson** [comment]
Internally the private channel uses pusher.sendEvent. I am not sure if things have changed on Pushers end that would allow you to get away with using that to send your data on a public channel, but you can give it a try. I know the javascript library was continuing to evolve fairly quickly.

**Comment by Seke1412** [comment]
var pusher:Pusher = new Pusher("868310468f8192695xxx","http://myDomain/testchat/");
var channel:Channel;
pusher.connect();
channel = pusher.subscribe("CHATROOM-0")
channel.bind("test-mess", testChannel)
channel.bindToClient("test-mess", toClient)

stage.addEventListener(MouseEvent.CLICK, mouseClick)

function testChannel(data){
    trace(data.user, data.content)
}

function toClient(data){
    trace(data)
       var d = {user:"CAN NGO", content:"HELLO"}
    //channel.dispatch("test-mess",d);
    pusher.sendEvent("test-mess",d,channel.name)
    //channel.trigger("test-mess", d)
}

function mouseClick(e:MouseEvent){
    var d = {user:"CAN NGO", content:"HELLO"}
    //channel.dispatch("test-mess",d);
    pusher.sendEvent("test-mess",d,channel.name)
    //channel.trigger("test-mess", d)
}

I've just try everything but it still won't work :(. I'm jumping out the window. Thank you smakinson.

**Comment by smakinson** [comment]
Maybe try setting it up just like the demo and verify that you are able to get that to work and make changes from there. This would include adding the serverside php for auth with pusher. That way you know everything is setup.
